name: ser_manos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.3
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.4.0
  firebase_auth: ^5.5.3
  intl: ^0.20.2
  geolocator: ^14.0.1
  share_plus: ^11.0.0
  http: ^1.1.0
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/
